// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsdL-1GyHkcu9q4iGzS2tw35SxfenYf0o',
    appId: '1:792327202166:web:c234ae2f4b12a7b247c657',
    messagingSenderId: '792327202166',
    projectId: 'portal-berita-923d9',
    authDomain: 'portal-berita-923d9.firebaseapp.com',
    storageBucket: 'portal-berita-923d9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb_3oyZk1iHcxtqugtWInS5E2sDPXnH18',
    appId: '1:792327202166:android:052da3b33d74dc0547c657',
    messagingSenderId: '792327202166',
    projectId: 'portal-berita-923d9',
    storageBucket: 'portal-berita-923d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7vXYmXYMCFX61nHT_dqB49SLjM_z5wXM',
    appId: '1:792327202166:ios:5c087dbe05638b3b47c657',
    messagingSenderId: '792327202166',
    projectId: 'portal-berita-923d9',
    storageBucket: 'portal-berita-923d9.appspot.com',
    iosBundleId: 'com.example.beritaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7vXYmXYMCFX61nHT_dqB49SLjM_z5wXM',
    appId: '1:792327202166:ios:5c087dbe05638b3b47c657',
    messagingSenderId: '792327202166',
    projectId: 'portal-berita-923d9',
    storageBucket: 'portal-berita-923d9.appspot.com',
    iosBundleId: 'com.example.beritaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsdL-1GyHkcu9q4iGzS2tw35SxfenYf0o',
    appId: '1:792327202166:web:dcf9198a9316cf6347c657',
    messagingSenderId: '792327202166',
    projectId: 'portal-berita-923d9',
    authDomain: 'portal-berita-923d9.firebaseapp.com',
    storageBucket: 'portal-berita-923d9.appspot.com',
  );
}
